let suggestions = [
'Prosus',
'British American Tobacco',
'Anheuser-Busch Inbev',
'Glencore plc',
'Compagnie Fin Richemont',
'Anglo American plc',
'Naspers Limited ',
'Anglo American Platinum Ltd',
'Firstrand Limited',
'MTN Group Limited',
'Vodacom Group Limited',
'Standard Bank Group',
'Capitec Bank Holdings',
'South32 Limited',
'Impala Platinum Holdings Limited',
'Kumba Iron Ore',
'Sasol Limited',
'Mondi plc',
'Sibanye Stillwater Limited',
'Gold Fields Limited',
'Absa Group Limited',
'Sanlam Limited',
'Anglogold Ashanti',
'Shoprite Holdings Limited',
'Bid Corporation Limited',
'Discovery Limited',
'Nedbank Group Limited',
'Aspen Pharmacare Holdings Limited',
'Pepkor Holdings Limited',
'Northam Platinum Limited',
'Remgro Limited',
'Rand Merchant Investment Holdings',
'Clicks Group Limited',
'Bidvest Group',
'Exxaro Resources Limited',
'Reinet Investments S.C.A.',
'Old Mutual Limited',
'Nepi Rockcastle plc',
'Investec plc',
'African Rainbow Minerals',
'Mr Price Group',
'MultiChoice Group',
'Woolworths Holdings Limited',
'Mediclinic International plc',
'Royal Bafokeng Platinum Limited',
'Growthpoint Properties Limited',
'The Foschini Group',
'Quilter plc',
'Distell Group Holdings',
'Harmony Gold Mining Company'

];